### ISSUE TITLE
Mailing lists are working!

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#10]
See https://lists.opentimestamps.org

Our previous HTTPS problems are fixed; the mailing list website is now using Lets Encrypt just like everything else. So let's add the links to them back to the website.

**Comment by RCasatta** [comment]
links readded!

**Comment by petertodd** [comment]
Great!

Now that there's ots-announce and ots-dev, lets change the title to say "mailing lists" too.

**Comment by RCasatta** [comment]
Done!
