### ISSUE TITLE
Add rust-opentimestamps link

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#11]
https://github.com/opentimestamps/rust-opentimestamps should be added to the Repositories section.

**Comment by RCasatta** [comment]
I added the link, we are going to update with a more appropriate one for rust when ready

**Comment by petertodd** [comment]
More appropriate one? I mean, I think it's ok if not all libraries in that section are equally advanced in their development.

**Comment by RCasatta** [comment]
Sorry I forgot the subject I was meaning the icon

**Comment by RCasatta** [comment]
icon added
