### ISSUE TITLE
We would like to join your member list.

### ISSUE THREAD

**Issue by OSDSP** [opentimestamps/opentimestamps.org#19]
Hi OTS Team

We appreciate your clever timestamping proof standard very much. To integrate your OTS as an additional anchor into our OSDSP service is just logic.
We would like to join your member list.
Product: OSDSP – PROOF YOURSELF
URL: http://OSDSP.com
Logo:
![osdsp 0-56-130](https://user-images.githubusercontent.com/31687865/30105548-3e18d702-92f9-11e7-8dad-d3eee5b382ec.png)

Best regards
Daniel

DANIEL MAYERTHALER ASSEMBLY
Im Grund 15
5405 Dättwil
Switzerland
Telefon: +41 79 686 38 56
info@osdsp.com

**Comment by petertodd** [comment]
Interesting! Got a english-language explanation of your service?

**Comment by RCasatta** [comment]
Even more interesting, this company and every company member has a logo in the tone of blue, perfect for the colors of our page :)

**Comment by OSDSP** [comment]
Here I send you a quick and dirty Chrome translation. Normally I just help my German speaking customers to understand Bitcoin and how they can handle this technology autonomically: www.BitcoinYourself.com. Of course I love to show my clients how they can handle tools like opentimestamps.org, quickhash-gui.org, cryptograffiti.info, proofofexistence.com themselves .Last year one customer thought it would be nice to have a secure simple user E-Mail service for proof of existence. This was the reason why I started www.OSDSP.com to evaluate the need for such a timestamping service.

Daniel
[OSDSP.pdf](https://github.com/opentimestamps/opentimestamps.org/files/1284217/OSDSP.pdf)

**Comment by OSDSP** [comment]
This is how our simple, weekly E-Mail service works:

1.
We remind our OSDSP flat rate customers every Friday, that Monday 12:00 is the deadline to send a master-hash for the recording into the OSDSP register.

2.
Over the weekend the customer has enough time to create, for example with https://quickhash-gui.org/, a CSV file containing all file hashes of a complete data archive. Finally the customer creates his master-hash of the CSV file. Of course all this steps can be fully automated.

3.
We remind our customers on Monday morning again.

4.
The customer sends an E-Mail
to: info@osdsp.com
Subject: #1701-0 (customer ID)
Message: 2F53EAE88777358E7E1099B5DD4A9666203C0A5DB7E9C954D4D66EBD4E91F941 (sample of a master-hash, we record the first line of text)

5.
We replay to the customers a secure PDF report OSDSP-170911.pdf (OSDSP OFFLINE-BACKUP), containing the OSDSP register (CSV file) with all master-hashes, a link to the BTC transaction and the OTS proof.

German speaking customers have access to PDF documentations and training videos (German sample: https://www.youtube.com/watch?v=Ycv9O-K40mA)

And that's all!

Daniel

![register](https://user-images.githubusercontent.com/31687865/30338877-6462712c-97ed-11e7-8712-d6560426c1fd.png)
[OSDSP-170911.pdf](https://github.com/opentimestamps/opentimestamps.org/files/1296763/OSDSP-170911.pdf)

**Comment by RCasatta** [comment]
Just added your company to the members list

**Comment by OSDSP** [comment]
Thank you for adding OSDSP.
Just one cosmetic amendment: The OSDSP Link on your page points into nirwana. Cool would be: http://www.osdsp.com/

One more question:
May I place your Logo on http://www.osdsp.com/? Check: Preview.png

Daniel
![preview](https://user-images.githubusercontent.com/31687865/30797682-296bdb32-a1d7-11e7-9182-c8bad9306c65.png)

**Comment by RCasatta** [comment]
ooops, link fixed.

Yes, it's ok if you add the logo
