### ISSUE TITLE
Connection closed when asking for the INFO of an upgraded ots file

### ISSUE THREAD

**Issue by Udala** [opentimestamps/opentimestamps.org#21]
I have uploaded an ots file on the VERIFY section. I generated that ots file with the command line client:
`ots upgrade bitcoin.pdf.ots`

When I press the INFO button, the website crashes. However, if I run `ots info bitcoin.pdf.ots` on the command line client, the results are shown correctly.
I attach the ots file in zip format if you want to replicate the problem.

[bitcoin.pdf.ots.zip](https://github.com/opentimestamps/opentimestamps.org/files/1435569/bitcoin.pdf.ots.zip)

**Comment by petertodd** [comment]
What do you mean by "the website crashes"?

**Comment by Udala** [comment]
The "website crashes" was not a fair description by me. The correct statement would have been the one on the title: "Connection closed" when asking for INFO of an upgraded ots file.

Here is a snapshot after the ots file has been uploaded.
![img1](https://user-images.githubusercontent.com/18075915/32466526-82199972-c347-11e7-8ffb-7e07ba8cea2c.png)


Here is a snapshot after having pressed the INFO button (unexpectedly closed the connection):
![img2](https://user-images.githubusercontent.com/18075915/32466570-a207fdf0-c347-11e7-9c9b-eb188e5cdd6d.png)

**Comment by petertodd** [comment]
Interesting! I think I can replicate this problem on Firefox, although the details are slightly different - I dont get a "ERR_CONNECTION_CLOSED", but rather the info button just does nothing.

That's a particularly large OTS file, so maybe you hit an internal limit in the implementation?

@RCasatta Thoughts?

**Comment by RCasatta** [comment]
The problem was in the default configuration of the web server (nginx).
We were stuck by using a wrong config param but now the support [answered](https://trac.nginx.org/nginx/ticket/1420) with the correct parameter to use.
Now the problem looks fixed, please open the link inside this [gist](https://gist.github.com/RCasatta/b8a9ec2f1e8e6cc539c25f7b1ac77140) (the bitcoin.pdf.ots) to confirm it's working

**Comment by Udala** [comment]
I confirm the issue has been solved.
Thanks.
