### ISSUE TITLE
Don't show FAILURE error message when Pending

### ISSUE THREAD

**Issue by lclc** [opentimestamps/opentimestamps.org#23]
Hi guys

I use opentimestamps.org as a simple exercise case when demonstrating decentralized timestamping, so people get a feeling how it works. What is a bit confusing (same question gets asked everytime) is why it shows FAILURE if we create the timestamp and then verify in the right field.  It shows:

> FAILURE!
> 
> Pending or Bad Attestation

It would be nice if it says Pending only if it didn't fail yet. Thanks for considering :)

**Comment by petertodd** [comment]
Concept ACK!

**Comment by RCasatta** [comment]
Hey, we changed the site to show the message:

> PENDING!
> 
> Pending or Bad Attestation

Colored in yellow instead of red and with a gear icon instead of the cross.

The calendar API does not discriminate between a commitment which is in queue or one which was never stamped, so I think this is the best we can do.

Is that ok?

**Comment by petertodd** [comment]
We could fix the calendar API to be able to distinguish between those two states; it already returns different textual messages, and could return different HTTP response codes.

IIRC there was some discussion about doing this before; maybe just go ahead and make it happen?

**Comment by lclc** [comment]
Thanks @RCasatta , that's much better.
