### ISSUE TITLE
Elements sidechain and Opentimestamps integration

### ISSUE THREAD

**Issue by omarshibli** [opentimestamps/opentimestamps.org#24]
We are working on integrating elements sidechain with opentimestamps, the main purpose is to add another layer of integrity and transparency by leveraging opentimestamps for public data attestation over bitcoin network.

The idea is pretty simple:
Every new block will be stamped by openstimestamps.

Is this a good idea/direction? any input would be much appreciated.

**Comment by petertodd** [comment]
You mean every new sidechain block will be timestamped via OpenTimestamps?

Remember that a timestamp doesn't solve the double-spend problem; you might be better off using single-use-seals. Here's two articles describing them:

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-December/015350.html

https://petertodd.org/2016/commitments-and-single-use-seals

**Comment by omarshibli** [comment]
I was referring to something like what you proposed in bitcoin dev mailing list:
Scalable Semi-Trustless Asset Transfer via Single-Use-Seals and Proof-of-Publication
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-December/015350.html

First of all, much appreciated for your publication these are novel ideas indeed.
The idea is we are trying to adapt your proposal for Elements, elements is already solving the double spend problem, we want add the proof of publication mechanism over bitcoin network, and that's would be good solution for us that holds the same qualities in your proposal, trustless with respect to validity, trusted with respect to censorship resistance.

**Comment by omarshibli** [comment]
I will reiterate your words here: 
"allowing us to leverage a bit of consensus on one system to efficiently provide consensus for a whole world of other systems."
This describes what we are trying to do here, leverage a bit of consensus on bitcoin network to provide consensus on public sidechains through proof-of-publication mechanism, would be happy to hear your thoughts.

**Comment by petertodd** [comment]
Ah, you have the right idea, but OpenTimestamps simply isn't meant to solve that problem; OpenTimestamps is timestamping software, not a single-use-seal implementation.

**Comment by omarshibli** [comment]
According to my basic understanding, OpenTimestamps is a carbon dating commitments with bitcoin, which might solve proof-of-publication, in the design proposed in bitcoin mailing they are two pieces single-use-seals and proof-of-publication, wouldn't opentimestamps be a valid option for the second part.

**Comment by omarshibli** [comment]
ok find this one https://petertodd.org/2014/setting-the-record-proof-of-publication#proof-of-publication-is-the-same-as-timestamping
I think I need more work here, thanks. ignore my previous message.
