### ISSUE TITLE
Verifying the timestamp of an empty file fails

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#26]
E.g. the https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/empty.ots example.

**Comment by lvaccaro** [comment]
Fix empty file at https://github.com/opentimestamps/opentimestamps.org/commit/b8c8e3c84cf0d4ec9733e62a8f2f4b8fdd1a1050 commit

**Comment by petertodd** [comment]
Looks good.
