### ISSUE TITLE
Verifying a dual-blockchain timestamp fails

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#27]
Specifically, https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/different-blockchains.txt / https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/different-blockchains.txt.ots

**Comment by RCasatta** [comment]
To support multiple attestations type in the library, we are waiting https://github.com/opentimestamps/javascript-opentimestamps/pull/16/ which is waiting for https://github.com/opentimestamps/python-opentimestamps/pull/20

In the meantime we just going to support dual-blockchain by ignoring non-bitcoin attestations

**Comment by lvaccaro** [comment]
* Merged opentimestamps library at https://github.com/opentimestamps/javascript-opentimestamps/commit/f6f42474647f4f425f02e2bebd47a4690f0cc8c8
* Update library and print multiple chain at https://github.com/opentimestamps/opentimestamps.org/commit/158568204b816613a50925e96c0fb2857045b1b2
* Example of file [ltc-and-btc.txt](https://github.com/opentimestamps/javascript-opentimestamps/blob/master/examples/ltc-and-btc.txt) stamped on litecoin & bitcoin and proof [ltc-and-btc.txt.ots](https://github.com/opentimestamps/javascript-opentimestamps/blob/master/examples/ltc-and-btc.txt.ots)

<img width="570" alt="screen shot 2018-03-26 at 18 40 42" src="https://user-images.githubusercontent.com/11627784/37919959-ca600224-3125-11e8-9f4a-320802687c90.png">

**Comment by petertodd** [comment]
Nice work!
