### ISSUE TITLE
SHA1 verification failure

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#29]
Specifically https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/sha1/a / https://github.com/opentimestamps/opentimestamps-client/blob/master/examples/sha1/a_or_b.ots

IMO we should support this, because [SHA1 Is Broken, But It's Still Good Enough for OpenTimestamps](https://petertodd.org/2017/sha1-and-opentimestamps-proofs).

**Comment by lvaccaro** [comment]
Add hashing functions at https://github.com/opentimestamps/opentimestamps.org/commit/158568204b816613a50925e96c0fb2857045b1b2
Now ots proof supports : Sha1, Sha256, Ripemd160 .
```
getSupportedTypes(){
	return ["SHA1","SHA256","RIPEMD160"];
},
```

**Comment by petertodd** [comment]
Looks good.
