### ISSUE TITLE
Error message when trying to verify without a file doesn't make sense

### ISSUE THREAD

**Issue by petertodd** [opentimestamps/opentimestamps.org#30]
To reproduce, upload a `.ots` proof file *without* uploading a file, and click on `Verify`.

Results in the unhelpful error message: "Not found hash type"

This should instead say something like "No file to verify; upload one first".

More generally, it'd probably help if we made the verification process separate in the UI to timestamping by duplicating the file upload button to make it clearer that you need both file and proof. The timestamp decoder can then be a third thing.

**Comment by RCasatta** [comment]
We updated the unhelpful error message.

In a rethinking of the process we propose to reorganize the page like that. 

Keep the current Stamp&Verify section as a separated page, with other buttons (like upgrade). This page will be reached from an "advanced" link from the new Stamp&Verify section.

The simplified Stamp&Verify section will contain a single file drop area.

- If the user drop or select any file which is not an ots receipt, the stamp process is automatically called and a receipt automatically downloaded.
- If the user drop or select an .ots receipt then another drop area will appear asking for the timestamped data. When the user drop or select the timestamped data the verify process is automatically called.

**Comment by petertodd** [comment]
That all sounds good to me!
