### ISSUE TITLE
Does OTS stamping point to multiple blocks?

### ISSUE THREAD

**Issue by OSDSP** [opentimestamps/opentimestamps.org#34]
Hello OTS team

When verifying stamps (--wait or upgrade) via web browser or "ots v" I noticed that sometimes different block numbers result. Here I send you all test files and ScreenDumps. 
It could be confusing for users if stamping is viewed in different blocks. It would be cool if all verification variants always show the lowest block number.

Daniel

PS: Many thanks for your fantastic OTS standard! I believe that everyone should take advantage of the OTS opportunity and that's exactly the message I'm spreading...
[OTS Test for OSDSP 2018-05a.zip](https://github.com/opentimestamps/opentimestamps.org/files/2028150/OTS.Test.for.OSDSP.2018-05a.zip)

**Comment by lvaccaro** [comment]
Hi Daniel, the problem is on [javascript-opentimestamps](https://github.com/opentimestamps/javascript-opentimestamps) library at line
[src/open-timestamps.js#L296](https://github.com/opentimestamps/javascript-opentimestamps/blob/aa55b423722eb3aa49f644154c71444ffd34cf5e/src/open-timestamps.js#L296) when sorting the attestations. We are fixing and adding your test into default unit test.

**Comment by OSDSP** [comment]
Hi Luca, now I'm impressed with your quick reaction. Very professional! Thank you

**Comment by lvaccaro** [comment]
Hi Daniel, the commit 661cddde1bb8052f47f3a84929345f93248ffa9f resolve your issue on [opentimestamp.org](https://opentimestamp.org) . Could you retry please?
In [javascript-opentimestamps lib](https://github.com/opentimestamps/javascript-opentimestamps) , the [016955be9173603c6493ea6cfbee682a9b30ea1e commit](https://github.com/opentimestamps/javascript-opentimestamps/commit/016955be9173603c6493ea6cfbee682a9b30ea1e) fixes the sorting function.
Your plain test & ots files are added to test suite: [osdsp.txt](https://github.com/opentimestamps/javascript-opentimestamps/blob/master/examples/osdsp.txt) and [osdsp.txt.ots](https://github.com/opentimestamps/javascript-opentimestamps/blob/master/examples/osdsp.txt.ots) .

**Comment by OSDSP** [comment]
Hello, Luce, I've already started testing. I'll run some tests and I'll send you a documentary afterwards.

**Comment by OSDSP** [comment]
[OSDSP-180523 (PERFECT MATCH).zip](https://github.com/opentimestamps/opentimestamps.org/files/2032742/OSDSP-180523.PERFECT.MATCH.zip)

Hi Luca, I tested the five old stamps and five new ones. I have a 100% match. Perfect! 
Thank you for the incredible support.

OTS consulting becomes my new favorite topic: http://www.mayerthaler.net/osdsp/personal_ENG/

Daniel
