### ISSUE TITLE
Browser-based verification fails due to bitcoin block height not found

### ISSUE THREAD

**Issue by dhimmel** [opentimestamps/opentimestamps.org#46]
I attempted verification of the following timestamp / file:

+ proof: [`manuscript.pdf.ots`](https://github.com/greenelab/scihub-manuscript/raw/gh-pages/v/17dd2015ec9396e59cdbc3c2b0abb7d33481bcbf/manuscript.pdf.ots)
+ stamped file: [`manuscript.pdf`](https://github.com/greenelab/scihub-manuscript/raw/gh-pages/v/17dd2015ec9396e59cdbc3c2b0abb7d33481bcbf/manuscript.pdf)

And got the error:

```
FAILURE!
bitcoin block height 476908 not found
```

Here's a screenshot of the website:

> ![image](https://user-images.githubusercontent.com/1117703/58736357-7f5e5880-83cb-11e9-84de-bfb6dd441d87.png)

My browser console contained many error messages, consisting of:

```
Failed to load resource: the server responded with a status of 404 ()
opentimestamps.org/:1 Access to fetch at 'https://www.localbitcoinschain.com/api/block-index/476947' from origin 'https://opentimestamps.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
opentimestamps.min.js:2 Insight response error: RequestError: TypeError: Failed to fetch
(anonymous) @ opentimestamps.min.js:2
```

Would love to get this working since I want to show a screenshot in an upcoming presentation about how we use OpenTimestamps for [Manubot](https://manubot.org).

**Comment by lvaccaro** [comment]
Hi, all these kinds of issues should be solved with updating js library, made in commit 056502d4cebb525a6d2c8e4926bad8cd867cb7d0 . Most block explorers are unreliable, and js library migrate to use https://blockstream.info

**Comment by dhimmel** [comment]
I just retried the verification on https://opentimestamps.org/ and it succeeded:

> ![image](https://user-images.githubusercontent.com/1117703/74554957-abeddc80-4f28-11ea-9238-bd454c24d067.png)

Thanks @lvaccaro for switching the block explorer to a more reliable one. So now you expect the "block height not found" error to be less frequent?
