### ISSUE TITLE
What happened to opentimestamps.org/tools ?

### ISSUE THREAD

**Issue by steffes** [opentimestamps/opentimestamps.org#51]
https://opentimestamps.org/tools is currently 404. [EternityWall's Blog Post](https://blog.eternitywall.com/2018/03/26/js-opentimestamps-by-example/) from 2018 has a screenshot of opentimestamps.org/tools : 
<img width="1139" alt="opentimestamps-org-tools" src="https://user-images.githubusercontent.com/943252/73601989-38fc6300-4531-11ea-8924-24f24844476f.png">

Does this still exist? I'm not seeing any files in the git history of this repo about tools. I find this useful as an easy way to quickly check hash data in hex format because I'm storing my timestamps as hex and not ots files.

**Comment by lvaccaro** [comment]
Hi @steffes, you could find the repo at https://github.com/lvaccaro/javascript-opentimestamps-tools and a demo version is available at https://lvaccaro.github.io/javascript-opentimestamps-tools/
