### ISSUE TITLE
Request to insert our logo and url

### ISSUE THREAD

**Issue by carlobrezigia** [opentimestamps/opentimestamps.org#52]
Hi, we are developing a platform for notarizing documents using the opentimestamps protocol. We are in beta test and we will be live at the end of may. We would like to insert our logo and url 

www.stampiz.io 

![STAMPIZ](https://user-images.githubusercontent.com/64354646/80303861-25207000-87b3-11ea-8588-44a444aaaa24.png)

**Comment by RCasatta** [comment]
Hi @carlobrezigia, we require a backlink from your site to opentimestamps.org site to be added to member sections, please see https://github.com/opentimestamps/opentimestamps.org/issues/2

**Comment by carlobrezigia** [comment]
Hi Riccardo, maybe you remember me ... I'm Carlo Brezigia ex CISO of Banca Intesa. We worked together on the project with De Loitte, Ethernity Wall and Ferdinando a few years ago. Now I have my own consulting firm. With Roberto Giorgetti, think knows you well..., we are building this notarization platform, almost as a hobby. Do you have a standard or any particular indication for the backlink? We will be ready with the beta version in a few weeks, then we will decide how to evolve. Nice to have found you again :-)

**Comment by RCasatta** [comment]
Sure I remember you and Roberto very well. I am happy you are working on a notarization platform with OpenTimestamps.
There are no strict requirements for the backlink, ideally you can include a logo https://github.com/opentimestamps but it is not mandatory. The official case of the letters is OpenTimestamps (O and T are the only uppercases)

**Comment by carlobrezigia** [comment]
Thanks Riccardo. We inserted OpenTimestamps logos and links into our page where we explain how the service works.   https://stampiz.io/come-funziona/   Do you need more information to be included in your members page? Thanks. Carlo

**Comment by RCasatta** [comment]
Looks good, Stampiz added

**Comment by carlobrezigia** [comment]
Thanks a lot 👍
