### ISSUE TITLE
website no longer showing pretty detailed breakdown of OTS proofs

### ISSUE THREAD

**Issue by n1bor** [opentimestamps/opentimestamps.org#54]
Issue is just when you drag/drop an OTS then file on the website then click on the (i) link the next page with the pretty breakdown of the proof does not load.

Thanks

**Comment by RCasatta** [comment]
I did a quick check now, and it appears to work from here with firefox and chrome, do you have more details?

**Comment by n1bor** [comment]
I am generating the OTS with the java api in an app.... so maybe I am corrupting them then.
I will try with some clean ones - and if they work issue must be my side.
Thanks for checking... I did not think they were corrupt as the initial page thinks they are fine and valid.
Only the detailed breakdown fails.

**Comment by n1bor** [comment]
Found issue. My OTS is big - 3274 bytes. This gets doubled to 6548 character in Hex.
But the getParameterByRoute function only returns the 1st 4087 characters.

And issue is ```url = window.location.href;``` is only returning that many..
And when I look in internet most say 2048 is limit... so needs a re-engineer I think?

Debugs in Edge - Chrome seems to die before I could get into the devtools...

Below is an OTS as an example.

```https://opentimestamps.org/info/?004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401082b418263e2600bcfe546080c07251adb0df1b75981ad536cff7ee4a4ab883447f010bd7060900f6d100e14595549e3c961bd08fff010142bb7c2ca629e8e20e0652e5e80500a08f1045ee161bff008404ba3a0b35c72e6ff0083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f726708f12013a1c33b392323048b430653d3c955e73adf92a2d1e7040dd3ac081ae2ae7e4a08f120137e0dd2e61b78051abcffa8863aeed7923293b68ea5206bb23c7f8616b63fdc08f0207c52863e9dda31e64a6b378c3e9596134ff62e15f6df48764a64b179a1298c7708f02004d49ae63e269e4a402d125005fd18b6714c31a33c8ae8bc6d5e3337628ec9b208f020e0d8642b0e2623189f8d942e8ee10822065d4fd931dced92218cb22671bb40ba08f020aeb9ae0ed0d58fdcb50b94db87d2de6a1d8996bf6799845e151f5f4a7e06350f08f120bb1781c35c9f9b94e9c2ef53c7210add910f0fc6c1998071d6f5dbfee5ab3c3e08f120966d9d3f023f56b69ec7be57d2dcee3cab06cf519f2b01297456645cc685e85708f1207bbc7ffb81edb76ac50f86ca52e006168fa5de763a5961c106ecf9540f6956d208f12032f3be521e40fe4192c04435d721875a24213dac9544140ec036d8624e972d2808f020aa96149cd921be5e15200f30aec6bfc12763543ec6371fcd3ef2a118dcd3854208f020a2a0affce779fd6d17f464e959fac4e5021db089c3527dcca39bb286a58c234d08f17101000000018f215a7a8fac602d835b4a9c04f60a89c01c6cb199ff43bec6240ad443fe434c000000001716001472b9ad43c8f3d1ae6b64e315c9ab9db39a373cf9fdffffff02dbf702000000000017a914da4050d6f6d28923e77473b12239a63e47aae7f7870000000000000000226a20f00405ad09000808f1208d2bf07b43736675afa06012fc5f12a9729af54480b3d1fac980d405ed43d2330808f12080d4de658ebf910e37042ece18ef8e3287113d0f85235c59a54496cc6dd8fab80808f020fe72d0df5de2dfda826bd8d63249956653ac5a0433e5dd64399e023cc0fab5a60808f1202b7bbc6cd7d452a2d26cd156a254cfb99b91db8b92db212ea249ec01d51f3e990808f0205b9e98ba2dd6613d9a73df4909bb82044554144e8c3d9143aba426934a7384000808f020d58673cbd988d3568f36ac6b494a0c338478b12958213bd929e20332d58e6d560808f02004af9dbe13d7db92a78c8cea2b2a4eb9d46d7b7374ea974bc1a83eb265f0a0c50808f02022ef4ba81e6f93a864d06d47ebb3b9d7ff986292ca3a34d709219c342160c5df0808f120dd704bed10f9559eddd2299d5832b9369e8f12111988176c583ca8d86a66ca640808f1200610310cb7a2f6d5c1fe0d23f7ebfaeb00664fa8eb326d7bf28be21516e8a7940808f1205f2c415b885d31c954a8894a8b5160f320c3cb1edc71ec3aad698f942a8cb87d0808f020e60e86b449f89d00e638bb2b3f799fc9e4d5575cc2d722e965ea18c15144156a0808000588960d73d719010386da26fff0109bc2608c649e5b9e536b4cc456a7ebb608f1045ee161bff0089925a8973f605d03ff0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d08f020e54673cb1f46d4386dc3037c615dfa40bc4116b8bc293075153c789fbd55887608f1201de3b8411e65d78e4554756cedcf7210c6d4528cf41f9fc35e53ba16dde55ada08f02016f35cf461087fd2bed4fb5d682e2e1311bc9b19a986e1a2fad2a0d2cb65b9ad08f1205b70f99869a5f8b89b884339939df9b0d57ea85ba34a132457332e53487f630d08f0207d6ccc43240c6309c90367d3a1c3b98eb3ea395b564a694803d5566e9d72f77d08f020a04908d9a441a699d2bd5c1f279ee0ccaab8f5e3043afa93fb8d86eacd863acd08f0206a01fdfc3b4d9646c66f967740773f88098eb63c8f217e5707a939072e9ca3ab08f12068b39e090141a1747db539dfa738c5334b3b6caa7c3fcb5dabcf5e442817010b08f120f03960f82c8925caf2071ed71b0bb9055d01c1230dffa072f6dec80d26f439b408f120389f7a39072b7d95408fdf01080fe4090fe61cff4e7ab680266cc394d8ec507308f020e7104e695f6419baf997387753ebe13b15bfac649e6476f4486bf2ecaf81501b08f020c64217ac45dcfb7aa88b86ed6e4c6006f03bab9917de70d0cdfe7cbfb40da38408f1590100000001cbf7a76569ec6b2b22fbd9a3b1ef50ebed5bf8e35d1963e578b7e2577a479b810000000000fdffffff021e8a0500000000001600141ad5428e1b8840aa95e69ba652c9c46c75c9097d0000000000000000226a20f00406ad09000808f020a54c3106894e4803b3508cb4108b3452001b0dfd8fd5d348d8f5784853bd64d40808f1205399047ff8060f29c5664db31eebb583799a465cd9d8e255b5e00c5706f2e7020808f020383c5db8b1b9d1aa7dcef9eda36d9f401d13d4d6ef65ca477c4d9a42bc739a990808f020993d211feaa1bb37b6c3ff76feb659c532734cf0c36097a27bc090e57ec1dc970808f02090f9b40d7b7e65398d155cb256300286e76fd654c0bf24dfda9dcf7fba324db10808f0209e605a56084a8de91e6c3fc97e23ddc0982f858dc2ffc9060e551192b1dc4a0b0808f0209008e4e942a11899031528a667e8f8683e0b6ddfbe007d6250cecf9a8b4349720808f120c04d1d32abfe3f8f61886f5b7cba8aa1288```

**Comment by n1bor** [comment]
Guess workaround is to only request 2 calendar servers?

**Comment by RCasatta** [comment]
have a look at the prune subcommand

**Comment by Singtah** [comment]
> have a look at the prune subcommand

Where is this subcommand ? 
Having the same issue here. File gets correctly deserialized on the main front page (drag and drop) as it indicates the bitcoin anchor properly.
However the /info page fails to load

**Comment by RCasatta** [comment]
prune command is available in the ots cli tool https://github.com/opentimestamps/opentimestamps-client

however, we are soon pushing a change on the web-site which will show the proof inside the home page https://github.com/opentimestamps/opentimestamps.org/pull/56

**Comment by RCasatta** [comment]
#56 merged and deployed on opentimestamps.org

feel free to comment or re-open if any issue arise
