### ISSUE TITLE
Timestamping hex digest and ots not working

### ISSUE THREAD

**Issue by RebekkalPangras** [opentimestamps/opentimestamps.org#61]
Hi, I tried to verify a SHA256 hex digest directly by requesting the URL with the digest and OTS hex in the get parameter. But that does not seem to work.

The following is the link I used and the resulting output screenshot.

file digest = 3d92059f570ef7c5ffab9c354b32d493531d20b435e7539e98be95d7635c880e
ots hex = 004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401083d92059f570ef7c5ffab9c354b32d493531d20b435e7539e98be95d7635c880ef010dbe10fd0a63c07ff99cd6802fa22161308fff01044c3508f9843d476532e6a074ec265a008f1205fe5a9ca2e1fd70dfd7c8cc93099401de5da0ce0c7fa84ee3e6b2d82ba6246e408f10460d9a489f008b2c3b4c85b3337df0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff01073f1ef2223eb708416b7c479222fb92508f120d8ba4a5893b61b8c57c053fcbd6d73028a2121e6d3605cf7d7ce24e858665eeb08f10460d9a489f0089431d242d4d16b450083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010ce051c101d28639a2c8a519329b5e10708f10460d9a489f008e8ccf42f5a8ece3c0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d

[https://opentimestamps.org/?digest=3d92059f570ef7c5ffab9c354b32d493531d20b435e7539e98be95d7635c880e&algorithm=SHA256&ots=004f70656e54696d657374616d7073000050726f6f6600bf89e2e884e8929401083d92059f570ef7c5ffab9c354b32d493531d20b435e7539e98be95d7635c880ef010dbe10fd0a63c07ff99cd6802fa22161308fff01044c3508f9843d476532e6a074ec265a008f1205fe5a9ca2e1fd70dfd7c8cc93099401de5da0ce0c7fa84ee3e6b2d82ba6246e408f10460d9a489f008b2c3b4c85b3337df0083dfe30d2ef90c8e2e2d68747470733a2f2f616c6963652e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267fff01073f1ef2223eb708416b7c479222fb92508f120d8ba4a5893b61b8c57c053fcbd6d73028a2121e6d3605cf7d7ce24e858665eeb08f10460d9a489f0089431d242d4d16b450083dfe30d2ef90c8e2c2b68747470733a2f2f626f622e6274632e63616c656e6461722e6f70656e74696d657374616d70732e6f7267f010ce051c101d28639a2c8a519329b5e10708f10460d9a489f008e8ccf42f5a8ece3c0083dfe30d2ef90c8e292868747470733a2f2f66696e6e65792e63616c656e6461722e657465726e69747977616c6c2e636f6d](url)

![image](https://user-images.githubusercontent.com/19290628/123831414-edb2d380-d921-11eb-8fce-4b2a835062ff.png)

Is there any solution for the above problem? 
Thanks

**Comment by anand10717** [comment]
Update on the above issue.

File name is undefined in the upgraded file download function. OTS contents are assigned to Proof.data field from the URL params but file name left unassigned. 

Does this related to the issue?

![download](https://user-images.githubusercontent.com/16556974/123902901-4c606780-d98b-11eb-8140-861c38557078.png)

**Comment by RebekkalPangras** [comment]
Hi @RCasatta is there any update for this issue? 

Thanks

**Comment by RebekkalPangras** [comment]
Fix for the above problem is done in Pull request #62
