### ISSUE TITLE
End of Life or Support of OTS

### ISSUE THREAD

**Issue by RebekkalPangras** [opentimestamps/opentimestamps.org#63]
Hi, I would like to know if we can expect End of Life or End of Support for Opentimestamps. Thanks.

**Comment by petertodd** [comment]
On Tue, Jul 13, 2021 at 02:37:45AM -0700, Rebekkal wrote:
> Hi, I would like to know if we can expect End of Life or End of Support for Opentimestamps. Thanks.

I expect OpenTimestamps to continue indefinitely. While the software hasn't had
to many updates lately, that's due to lack of need to change anything rather
than lack of maintenance.
