### ISSUE TITLE
502 Error on OpenTimestamps.org

### ISSUE THREAD

**Issue by dominic-p** [opentimestamps/opentimestamps.org#67]
Hello, I'm sure the team is aware of this, but I wasn't able to find anything about it after a quick search. The site has been down for a bit, and I was wondering if there is any news on the cause.

It appears that the official calendar servers are still up from some basic testing.

**Comment by petertodd** [comment]
On Tue, Jun 04, 2024 at 10:12:16AM -0700, Dominic wrote:
> Hello, I'm sure the team is aware of this, but I wasn't able to find anything about it after a quick search. The site has been down for a bit, and I was wondering if there is any news on the cause.
> 
> It appears that the official calendar servers are still up from some basic testing.

This should be fixed now, thanks!

**Comment by dominic-p** [comment]
Awesome! Looks good to me. I love OpenTimestamp, btw. Thank you so much for creating it. :)
