### ISSUE TITLE
How-it-works sentence doesn't parse

### ISSUE THREAD

**Issue by jafaber** [opentimestamps/opentimestamps.org#9]
I was thinking of pitching this project to someone and giving them a link to opentimestamps.org, but one of the most important first-impression sections of the front page "How it works" doesn't make sense IMHO.

> A timestamp*s* proves that some data existed prior to some point in time

A timestamp (singular, I guess).

And then end of sentence, not comma.

> , OpenTimestamps defines a set of operations to describe a timestamp *which* could be done in different way. 

I don't think anyone not already familiar with OpenTimestamps would understand that. It's been a while since I last looked at it myself, but maybe something like:

> OpenTimestamps defines a set of operations for creating provable timestamps and later independently verifying them.

Maybe throw in "flexible" somewhere instead of "could be done in different way" if necessary. Not sure you need to go into such details in the introduction.

**Comment by RCasatta** [comment]
Thanks @jafaber 
I made the corrections, let me know what do you think and if you find other texts which is not clear

**Comment by jafaber** [comment]
Looks good to my layman eye. Thanks.
